# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
    - dev

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: Build and publish
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: 'DockerHubConnection'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        repository: 'verak13/mealforfamilytest'
        tags: |
          latest
    

- stage: Dev
  variables:
    ConnectionStrings.DefaultConnection: $(ConnectionStringDev)
  displayName: Deploy to Dev
  condition: contains(variables['Build.SourceBranch'], 'refs/heads/dev')
  jobs:
    - deployment: DeployDev
      environment: DEV
      pool:
        vmImage: ubuntu-latest  

      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: DotNetCoreCLI@2
              displayName: Install dotnet-ef
              inputs:
                command: 'custom'
                custom: 'tool'
                arguments: 'install --global dotnet-ef'

            - script: dotnet tool restore
              displayName: 'Dotnet tool restore'

            - task: DotNetCoreCLI@2
              displayName: Check dotnet-ef version
              inputs:
                command: 'custom'
                custom: 'ef'
                arguments: '--version'
          
            - script: |
                ls
                dotnet-ef database update --connection "$(ConnectionStringDev)"
              displayName: 'Dotnet-ef database update'

- stage: Prod
  variables:
    ConnectionStrings.DefaultConnection: $(ConnectionStringProd)
  displayName: Deploy to Prod
  condition: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
    - deployment: DeployProd
      environment: PROD
      pool:
        vmImage: ubuntu-latest  

      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: DotNetCoreCLI@2
              displayName: Install dotnet-ef
              inputs:
                command: 'custom'
                custom: 'tool'
                arguments: 'install --global dotnet-ef'

            - script: dotnet tool restore
              displayName: 'Dotnet tool restore'

            - task: DotNetCoreCLI@2
              displayName: Check dotnet-ef version
              inputs:
                command: 'custom'
                custom: 'ef'
                arguments: '--version'
                
            - script: |
                ls
                dotnet-ef database update --connection "$(ConnectionStringDev)"
              displayName: 'Dotnet-ef database update'
                

            - task: AzureWebAppContainer@1
              displayName: 'Azure Web App on Container Deploy'
              inputs:
                azureSubscription: 'name'
                appName: 'azure-mealforfamily-test-container'
                imageName: 'verak13/mealforfamilytest:latest'
                appSettings: '-ConnectionStrings__DefaultConnection "$(ConnectionStringDev)"'